-- Resolução virtual: o jogo mantém a mesma composição em qualquer janela.
VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288

GROUND_HEIGHT = 16
GROUND_Y = VIRTUAL_HEIGHT - GROUND_HEIGHT

PIPE_WIDTH = 70
PIPE_HEIGHT = 288
PIPE_START_X = VIRTUAL_WIDTH + 32

BACKGROUND_SCROLL_SPEED = 30
GROUND_SCROLL_SPEED = 80
BACKGROUND_LOOPING_POINT = 413

BASE_PIPE_SPEED = 72
MAX_PIPE_SPEED = 118
BASE_GAP_HEIGHT = 116
MIN_GAP_HEIGHT = 88
PIPE_SPAWN_INTERVAL = 1.65

BIRD_GRAVITY = 700
BIRD_FLAP_VELOCITY = -220
